POST http://localhost:8001/workout
Accept: application/json, text/plain, */*
Referer: http://localhost:3000/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Content-Type: application/json;charset=UTF-8

[
  {
    "id": "bdbb1033-08b9-46f2-b595-6d6922ebf9c5",
    "exercise": {
      "id": "d83e1f39-3e6c-450b-bee3-170dfb3c01d0",
      "name": "Bench press"
    },
    "order": 1,
    "sets": [
      {
        "weight": 60,
        "reps": 10,
        "order": 0
      }
    ]
  },
  {
    "id": "7ba2602c-f1d5-4c1c-9b4b-4899cdf6168d",
    "exercise": {
      "id": "8b07e987-7d6a-49d7-bf2b-88c99b75047f",
      "name": "Bench press"
    },
    "order": 2,
    "sets": [
      {
        "weight": 20,
        "reps": 10,
        "order": 0
      }
    ]
  },
  {
    "id": "ae5f3b8d-9116-4145-8517-3170294844c7",
    "exercise": {
      "id": "35d84598-fafc-4dcd-9ee7-560ec6fac8aa",
      "name": "Bench press"
    },
    "order": 0,
    "sets": [
      {
        "weight": 30,
        "reps": 0,
        "order": 0
      }
    ]
  },
  {
    "id": "70d730d7-29ac-4150-9766-aae44f140675",
    "exercise": {
      "id": "97b60d48-54c8-40fe-a301-11606c3b9afa",
      "name": "Rows"
    },
    "order": 3,
    "sets": [
      {
        "weight": 60,
        "reps": 6,
        "order": 0
      }
    ]
  }
]

###

