image: tiangolo/docker-with-compose

# services:
  # - docker:19.03.1-dind

stages:
  - precheck
  - cleanup
  - build
  - deploy

precheck-prod:
  stage: precheck
  script:
    - docker --version
    - docker ps -a
    - docker-compose --version
    - ls -al
  only:
    - master

cleanup-prod:
  stage: cleanup
  script:
    - docker rmi easyfit_app-client --force
    - docker rmi easyfit_app-server --force
    - docker stack rm easyFitStack
  only:
    - master

build-prod:
  stage: build
  script:
    - docker-compose --file docker-stack.yml build 
  only:
    - master

deploy-prod:
  stage: deploy
  script:
    - echo y | docker stack deploy -c docker-stack.yml easyFitStack
  only:
    - master