# image: docker:stable
image: tiangolo/docker-with-compose
# image: docker

# before_script:
  # - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - pre-check
  - build
  - cleanup
  - deploy

precheck-prod:
  stage: pre-check
  script:
    - docker --version
    # - docker run hello-world
    - docker ps -a
    - docker-compose --version
  only:
    - master

build-prod:
  stage: build
  script:
    - docker-compose build
  only:
    - master


cleanup-prod:
  stage: cleanup
  script:
    - docker stack rm easyFitStack
    - docker stack rm vote
  only:
    - master

deploy-prod:
  stage: deploy
  script:
    # - docker stack deploy -c docker-compose.yml --with-registry-auth my-stack
    # - docker stack deploy -c docker-compose.yml easyFitStack
    - docker stack deploy -c docker-stack.yml easyFitStack
    # - docker-compose up
    # - npm start --prefix ./frontend
  only:
    - master