image: tiangolo/docker-with-compose

# before_script:
  # - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  # - build
  - deploy

# build-prod:
  # stage: build
  # script:
    # - docker-compose build
  # only:
    # - master

deploy-prod:
  stage: deploy
  script:
    - docker pull debian
    # - docker stack deploy -c docker-compose.yml # --with-registry-auth my-stack
  only:
    - master