image: docker:stable
# image: tiangolo/docker-with-compose
# image: docker

# before_script:
  # - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - pre-check
  - build
  - deploy

precheck-prod:
  stage: pre-check
  script:
    - docker run hello-world
  only:
    - master

build-prod:
  stage: build
  script:
    - docker-compose build
  only:
    - master

deploy-prod:
  stage: deploy
  script:
    # - docker stack deploy -c docker-compose.yml --with-registry-auth my-stack
    # - docker stack deploy -c docker-compose.yml easyFitStack
    - npm start --prefix ./frontend
  only:
    - master