image: tiangolo/docker-with-compose

stages:
  - precheck
  - cleanup

precheck-prod:
  stage: precheck
  script:
    - whoami
    - pwd
    - ls -al
    - docker --version
    - docker ps -a
    - docker-compose --version
    - docker network ls

cleanup-prod:
  stage: cleanup
  script:
    - docker stack rm easyfit
    - sh scripts/cleanup.sh
  only:
    - cleanup