# image: docker:stable
image: tiangolo/docker-with-compose
# image: docker:19.03.1
# image: docker

services:
  - docker:19.03.1-dind
  # - node

before_script:
  # - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  # - apt install nodejs
  # - sudo apt install nodejs

stages:
  - pre-check
  - cleanup
  # - preinstall
  # - build
  - deploy

precheck-prod:
  stage: pre-check
  script:
    - docker --version
    - docker ps -a
    - docker-compose --version
    - ls -al
  only:
    - master

cleanup-prod:
  stage: cleanup
  script:
    # - docker rmi $(docker images)
    - docker rmi easyfit_app-client:latest --force
    - docker rmi easyfit_app-server --force
    - docker stack rm easyFitStack
    - docker-compose stop
  only:
    - master

# preinstall-prod:
#   stage: preinstall
#   script:
#     - pip install npm
#   only:
#     - master

# build-prod:
#   image: node
#   stage: build
#   script:
#     - pwd
#     - ls -al
#     # - npm install --prefix ./frontend
#     # - docker build ./react-docker -t react-docker
#   only:
#     - master

deploy-prod:
  # image: node
  stage: deploy # todo rename to build and deploy
  script:
    - pwd
    - ls -al
    - ls *
    - echo y | docker-compose --file docker-compose.yml build
    - echo y | docker stack deploy -c docker-stack.yml easyFitStack
  only:
    - master