image: tiangolo/docker-with-compose

services:
  - docker:19.03.1-dind

before_script:
  # - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  # - apt install nodejs
  # - sudo apt install nodejs

stages:
  - pre-check
  - cleanup
  - build
  - deploy

precheck-prod:
  stage: pre-check
  script:
    - docker --version
    - docker ps -a
    - docker-compose --version
    - ls -al
  only:
    - master

cleanup-prod:
  stage: cleanup
  script:
    - docker rmi easyfit_app-client --force
    - docker rmi easyfit_app-server --force
    - docker stack rm easyFitStack
  only:
    - master

build-prod:
  stage: build
  script:
    - docker-compose --file docker-stack.yml build 
    # - echo y | docker-compose --file docker-stack.yml build 
  only:
    - master

deploy-prod:
  stage: deploy # todo rename to build and deploy
  script:
    - pwd
    - ls -al
    - ls *
    - echo y | docker stack deploy -c docker-stack.yml easyFitStack
  only:
    - master