version: '3.7'

services:
  easyfit-api:
    image: mazaq/easyfit-api:0.2.0-SNAPSHOT
    build:
      context: easyfit-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://157.230.116.74:5432/easyfit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123!
    networks:
      - backend
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  easyfit-ui:
    image: mazaq/easyfit-ui:0.2.0-SNAPSHOT
    build:
      context: easyfit-ui
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:8080/api
    ports:
      - "9090:80"
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: easyfit
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123!
      # POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  db-data:

networks:
  backend:
  frontend:    
