version: '3.7'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: easyfit
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123!
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
      
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend
    restart: unless-stopped

volumes:
  db-data:
  pgadmin:

networks:
  backend:
