version: "3"
services:
  web:
    image: react-docker
    build:
      context: ./react-docker
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    networks:
      - backend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:

volumes:
  db-data: