version: '3.7'

services:
  ms-api:
    image: easyfit_ms-api
    build:
      context: ms-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "7000:7000" # debug
    restart: always
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: callicoder
      SPRING_DATASOURCE_PASSWORD: callicoder     
    networks:
      - backend
      - frontend

  ms-auth:
    image: easyfit_ms-auth
    build:
      context: ms-auth
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "7001:7001" # debug
    restart: always
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: callicoder
      SPRING_DATASOURCE_PASSWORD: callicoder     
    networks:
      - backend
      - frontend

  ms-client:
    image: easyfit_ms-client
    build:
      context: ms-client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:8080/api
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - ms-api
    networks:
      - frontend

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: polls
      MYSQL_USER: callicoder
      MYSQL_PASSWORD: callicoder
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
  
volumes:
  db-data:

networks:
  backend:
  frontend:    