POST http://localhost:8080/workout
Content-Type: application/json

{
  "exercises":[
    {
      "order":0,
      "exerciseId":2,
      "exerciseName":"Bench press",
      "reps":0,
      "weight":"20"
    },
    {
      "order":1,
      "exerciseId":3,
      "exerciseName":"Pullups",
      "reps":5,
      "weight":"None"
    }
  ]
}

###

GET http://localhost:8080/
Content-Type: application/json


###

GET http://localhost:8080/workout
Content-Type: application/json


