DELETE FROM TEMPLATE;
INSERT INTO TEMPLATE ( ID,  NAME,  IS_START_TIME) VALUES (1, 'Diet',TRUE);
INSERT INTO TEMPLATE ( ID,  NAME,  IS_START_TIME) VALUES (2, 'Health',TRUE);
INSERT INTO TEMPLATE ( ID,  NAME,  IS_START_TIME) VALUES (3, 'Habbits',TRUE);

